// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCixrnoVHV9BrvgvbB1kq82l6p3RPF8v84',
    appId: '1:563705057444:web:f12f011568e9b195cd9631',
    messagingSenderId: '563705057444',
    projectId: 'fetchproducts-e115c',
    authDomain: 'fetchproducts-e115c.firebaseapp.com',
    storageBucket: 'fetchproducts-e115c.appspot.com',
    measurementId: 'G-HJZ1D2PE1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXvI8_IFHMb5gdgz2cPXhcDSNgNB5xv5g',
    appId: '1:563705057444:android:d0dbcd49f25742ebcd9631',
    messagingSenderId: '563705057444',
    projectId: 'fetchproducts-e115c',
    storageBucket: 'fetchproducts-e115c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhrlut0RShtOL3FuhPNPW2AojIf6FWus4',
    appId: '1:563705057444:ios:0abada2694997eadcd9631',
    messagingSenderId: '563705057444',
    projectId: 'fetchproducts-e115c',
    storageBucket: 'fetchproducts-e115c.appspot.com',
    iosBundleId: 'com.example.fetchProduct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhrlut0RShtOL3FuhPNPW2AojIf6FWus4',
    appId: '1:563705057444:ios:862d3ae474853d49cd9631',
    messagingSenderId: '563705057444',
    projectId: 'fetchproducts-e115c',
    storageBucket: 'fetchproducts-e115c.appspot.com',
    iosBundleId: 'com.example.fetchProduct.RunnerTests',
  );
}
